### ISSUE TITLE
SSH: Prompt for username, password when not specified in connection settings

### ISSUE THREAD

**Issue by rss42** [GoogleCloudPlatform/iap-desktop#1227] opened 2024-01-11 03:33 UTC
Thank you very much for implementing [#743](https://github.com/GoogleCloudPlatform/iap-desktop/issues/743), really appreciated! 

Just a quick note that the new password based SSH authentication works great when username and password are _both_ saved in the IAP Desktop Connection settings, however the password method does not appear to be fully functional - if either one of those two values are left empty connection attempt drops immediately with "Authentication failed (username/password)". The (assumed) expected behavior would be to display a prompt which would allow for the username and password to be entered interactively.

Working:

1. Public key authentication - disabled ; Username - populated ; Password - populated

Not working:

2. Public key authentication - disabled ; Username - not populated ; Password - not populated
3. Public key authentication - disabled ; Username - populated ; Password - not populated

Please find attached the SSH server side debug outputs for all 3 of these scenarios. Note <LDAP_USER> is a valid external LDAP username, while <DEFAULT_OS_LOGIN_USER> is the default OS Login style username (which is not a valid username in this configuration).

[01_IAP_desktop_sshd_debug_username_populated_password_populated_OL_89.txt](https://github.com/GoogleCloudPlatform/iap-desktop/files/13896995/01_IAP_desktop_sshd_debug_username_populated_password_populated_OL_89.txt)
[02_IAP_desktop_sshd_debug_username_not_populated_password_not_populated_OL_89.txt](https://github.com/GoogleCloudPlatform/iap-desktop/files/13896996/02_IAP_desktop_sshd_debug_username_not_populated_password_not_populated_OL_89.txt)
[03_IAP_desktop_sshd_debug_username_populated_password_not_populated_OL_89.txt](https://github.com/GoogleCloudPlatform/iap-desktop/files/13896997/03_IAP_desktop_sshd_debug_username_populated_password_not_populated_OL_89.txt)

The O/S is Oracle Linux 8.9 and SSHD is OpenSSH_8.0p1 with OpenSSL 1.1.1k

**Comment by jpassing** [comment] 2024-01-15 07:07
Thanks for reporting this issue and sharing those details, I'll look into that.

**Comment by jpassing** [comment] 2024-01-17 04:36
I had a look at the logs that you shared and noticed that you used the authentication method `password`, not `keyboard-interactive`.

For `keyboard-interactive`,  IAP Desktop implements prompting and the expected behavior is:

| username | password | expected result |actual result in my tests |
| ---| ---| --- | --- |
| provided | provided | use provided username, ignore password (*), show prompts | :heavy_check_mark:|
| provided | empty | use provided username, show prompts |:heavy_check_mark:|
| empty | empty | use default username (**), show prompts|:heavy_check_mark:|

(*) IAP Desktop has no idea what the server is prompting for, so it won't try to use the stored password
(**) the default username is derived from the email address of your Google user account

For `password`, IAP Desktop doesn't implement prompting and the current behavior is:

| username | password | result |
| ---| ---| --- | 
| provided | provided | use provided credentials | 
| provided | empty | error message | 
| empty | empty |error message |

I guess what you're suggesting is to change that behavior to:


| username | password | result |
| ---| ---| --- | 
| provided | provided | use provided credentials | 
| provided | empty | use provided username, prompt for password| 
| empty | empty |use default username, prompt for password| 

Is that correct?

**Comment by rss42** [comment] 2024-01-17 19:11
On a closer look, yes it is indeed the `password` method that was used in our test and is also the method which is of the specific interest to us. That said, with public key auth disabled it is currently kind of tricky to tell from the client side which of the two alternative methods is actually being used – perhaps there is an opportunity to make that a little bit more apparent in the future versions of the Connection Settings GUI? One potential option that comes to mind, perhaps all 3 methods (`public key`, `password`, `keyboard-interactive`) could be part of the same drop-down menu? Just a thought :)

Regardless, I should have caught it in the server side logs, so apologies for that – I have corrected the title and the wording of the issue to better reflect what the question is about.

So, for the `password` method we would (ideally) like to have prompting implemented with the following behaviour:

| username | password | result
|------------|------------|------------------------------------------
| provided | provided | use provided credentials
| provided | empty    | use provided username, prompt for password
| empty    | empty    | prompt for username, prompt for password

In our scenario, the username used by the external LDAP is very different from the IAP Desktop default username (derived from the email address of user’s Google account) which is why defaulting to use the default username in the scenario where both fields are empty would not work for us. Unless, there was a way to custom modify the default username, however I suspect going down that path (even if technically feasible) would likely open up more challenges in other areas of IAP Desktop? So from our perspective, being prompted for username any time the field is empty would definitely be very acceptable.

**Comment by jpassing** [comment] 2024-01-18 04:38
> So, for the password method we would (ideally) like to have prompting implemented with the following behaviour:

I agree that this behavior would be better.

FWIW, the reason IAP Desktop falls back to a default username has to do [metadata-based keys](https://cloud.google.com/compute/docs/connect/add-ssh-keys). When you use metadata-based keys, the client has to specify a username, but that username doesn't need to match an existing account -- so deriving a default from the user's email address makes sense. But for `password` and `keyboard-interactive`, it would be better to show a prompt.

**Comment by jpassing** [comment] 2024-01-23 02:47
I now changed the behavior for authentication method `password`  as follows:

| username | password | result
|------------|------------|------------------------------------------
| provided | provided | use provided credentials
| provided | empty    | use provided username, **prompt for password**
| empty    | empty    | use default username, **prompt for password**

The password prompt looks like this:

![image](https://github.com/GoogleCloudPlatform/iap-desktop/assets/5724941/94ae28fd-f08c-4eb3-aae5-fe353dc441d9)

Early during the connection sequence, IAP Desktop queries the server for available authentication methods so that it knows whether to do `publickey`, `password`, or `keyboard-interactive` auth. This query requires IAP Desktop to specify a username, and the SSH server doesn't allow that username to be changed later. So by the time IAP Desktop knows that it needs to do `password` auth, it can't let the user modify the username anymore. So I had to keep the username behavior as is...

If you'd like to give it a try, [here's the link to a signed installer package for an early build of IAP Desktop 2.40](https://issuetracker.google.com/action/issues/321839395/attachments/51047848?download=true).

**Comment by rss42** [comment] 2024-01-23 04:14
Thank you so much for the very quick turnaround, as well as the new build that includes these enhancements related to the `password` SSH method!

Confirming that using the new build the following 2 scenarios work great and as we would expect:

| username | password | result
|----------|----------|--------------------------
| provided | provided | use provided credentials
| provided | empty    | use provided username, prompt for password

The 3rd scenario:

| username | password | result
|----------|----------|--------------------------
| empty	   | empty    | use default username, prompt for password

also works as you describe (i.e. assuming a default username based on user's Google account), which unfortunately means we won't be able to use it in our scenario. Understanding the background and reason behind having to be implemented that way, I am wondering if there is possibly a way to **bulk** populate credentials of all SSH connections in IAP Desktop? An operation which would basically do the following for all SSH connections in as few steps as possible:

1. flip `Public key authetication` to `Disabled`
2. populate `username` with a provided custom value

We tend to deal with very large number of VMs, so this would definitely help to sort of work around defaulting to using the default username in scenario when that field is not populated. 

And if it would be possible to similarly:

3. populate/change the `password` field 

that would be even more awesome, as that would be very helpful for our mandatory 90 day password changes :)

Apologies if this ends up being basically another feature request - if bulk `username` and `password` changes are not feasible, we will make do with what is currently implemented in this build, as that already makes IAP Desktop way more useable in our scenario with an external LDAP in place. Thanks again for all the work on this and IAP Desktop in general!

**Comment by jpassing** [comment] 2024-01-23 05:31
> I am wondering if there is possibly a way to bulk populate credentials of all SSH connections in IAP Desktop?

If you right-click a zone or project in the Project Explorer window and select **Connection Settings**, then you can set connection settings for the entire zone or project. Connection settings ["inherit down" from project to zone to VM](https://googlecloudplatform.github.io/iap-desktop/toolwindow-connection-settings/). So you only need to make these changes (disable `Public key auth`, populate `Username`) once per project. Would that work?

**Comment by rss42** [comment] 2024-01-23 08:00
Perfect - ability to inherit SSH connection settings from the project level looks very helpful, so yeah I believe that will work very well for our needs!

Thanks again for all your help!

**Comment by jpassing** [comment] 2024-02-23 01:53
This feature [is now available in version 2.40](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.40.1418), so I'll close this issue.

**Closed by jpassing** 2024-02-23 01:53 UTC
Labels: enhancement, next-release
