### ISSUE TITLE
Intermittent Connectivity Issues

### ISSUE THREAD

**Issue by jgustav1** [GoogleCloudPlatform/iap-desktop#610] opened 2022-02-09 18:15 UTC
Expected behavior:
* Stable RDP or SSH Connection

Observed behavior:
* Intermittent Connectivity Issues (I'll lose connection to the server ~ every 20 minutes and then it will automatically attempt to reconnect (RDP) or I'll have to manually reconnect (SSH))

<img width="727" alt="iap-connectivity-issue" src="https://user-images.githubusercontent.com/78444411/153263961-491b4808-7d67-4dc3-ae9a-dc0961f70b27.PNG">

<img width="728" alt="ssh-connection-issue" src="https://user-images.githubusercontent.com/78444411/153264022-b76b5dc6-2e10-4092-b35e-fbeac415a88e.PNG">

Installed version: 2.23.722.0
.NET Version: 4.8.4420.0
OS Version: Microsoft Windows NT 10.0.18363.0

**Comment by jpassing** [comment] 2022-02-10 07:40
This shouldn't happen... a few questions:
* Are you directly connecting to the internet, or are you connecting via a HTTP proxy server? 
* Is it always around the 20min mark that the connection is lost, or does the timeout vary a lot?

Because the issue seems to apply to both RDP and SSH, it seems unlikely that it's caused by configuration/policies on the VM.

**Comment by jpassing** [comment] 2022-02-15 07:39
It would be helpful if you could run the following experiment:

1. Open an SSH session to a VM instance using IAP Desktop and leave it open
2. Run `gcloud compute ssh INSTANCE --tunnel-through-iap`  to open another SSH session to the same VM instance, and leave it open
3. Wait 10-20 min


IAP Desktop and gcloud don't share any code. Therefore, if both sessions break around the same time, then the issue must be caused by the OS or network. But if the gcloud session survives and the IAP Desktop session breaks, then it must be IAP Desktop's fault.


Instead of only creating one session per tool, it would be even better to create 2-3 sessions using each tool.

**Comment by jgustav1** [comment] 2022-02-17 17:27
So I ran that experiment.

I opened 3 SSH sessions in IAP Desktop and 3 SSH sessions using gcloud

IAP Desktop lost connection to all 3 instances after ~5 minutes.

gcloud SSH sessions were still connected after the 20 minute mark.

**Comment by jpassing** [comment] 2022-02-24 13:28
Thanks for running these experiments. I did a few test myself over the past days, but so far I haven't been able to reproduce the issue -- the SSH sessions stayed connected over multiple hours.

> gcloud SSH sessions were still connected after the 20 minute mark.

Just to double check -- I assume the SSH sessions were also still responsive? I'm asking because putty occasionally likes to just freeze instead of showing a connection error.

**Comment by jgustav1** [comment] 2022-02-24 22:20
Yup, the SSH sessions were still responsive.

From: Johannes Passing ***@***.***>
Sent: Thursday, February 24, 2022 6:29 AM
To: GoogleCloudPlatform/iap-desktop ***@***.***>
Cc: Gustavson, Jarod ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [GoogleCloudPlatform/iap-desktop] Intermittent Connectivity Issues (Issue #610)


Thanks for running these experiments. I did a few test myself over the past days, but so far I haven't been able to reproduce the issue -- the SSH sessions stayed connected over multiple hours.

gcloud SSH sessions were still connected after the 20 minute mark.

Just to double check -- I assume the SSH sessions were also still responsive? I'm asking because putty occasionally likes to just freeze instead of showing a connection error.

—
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1wZUxZwRhth94WCdJbeMxKtHRRNV0cBkamF-P4uex9C7AtH3q6wPbJFRlXOIzjEnM2SgstojG7BJLinn3xTCxQBHdSpqsNl_wgbAz6lR4Xn0KK2-hmJeDuo1kPGQgR1p52ChPNqzMNzKd4x28tR_qi5cdN3Z1hMKAoAPo9OEE5-9OVk_Zjg_GFeXeBnU7-fgM3kSfJ5smph9Y8P-ohTsEyM-vbxb-UrXrdZthQgVFDvPv9W3AlK7sqK3hY9var2z8IKZAK1ORBYGbyRTQ-LAy-CX4za63CZVZIGO2ht3DO4zefkZIrhk9oeaCGS8lpt7fJyrRvpUJgzxkCy1grnpJ5ZExpLimmJ-vQgvRN0utG5ic8kP-I2Fk0bLWtl_CWajIHoRbXb1WsCOzPzqZZFQy7YS_xLy1FbU-8CbaJGs9fBnjMylfgb_oW972vcyUQchCFjVMpbGMyTm7-mKoSao40VNDvRHgAhr7Kb8GJGX5MejAFqYWwSD2C2VvqpdnZTPRW58XUik-YNFy9hNkgRdhDg/https%3A%2F%2Fgithub.com%2FGoogleCloudPlatform%2Fiap-desktop%2Fissues%2F610%23issuecomment-1049861557>, or unsubscribe<https://secure-web.cisco.com/11lJlpek0XSD5zm5RftbelsEm2PsdOHqylveKXFoDUgKb9R8Arpetz9QabNoAYMDHy2eV2cKmoMOOgFAULpch_CRd8x1eyKJ3sd5WZ0bmblX3V8dJAmj3ah-06VJ8eLRN2Jtb6wVn1bW5cLjQq9208b9qwCKyl-1G1bZMgAEErTB5uSeJpT1hE1xFxqREdjqo9QlSFoI1YVQFPrqyj-fDDOUb5MXktAP0bsMJ4_XbIUCW_qR4tUEoE7yRKlBLLp4eypECou48eJSifDymblF91TaeraaeNsJ6AFMZfFi0ghuvLFNUnBoou3XvzcwT6CQF0L77lBM1QyUrn6YyiY_svW91Su221QwBRpkESa1A9XCktgrxe0stQe0IChKst9CVTIARDsIjk6WqgAVwCX-f_p8mvtyOFhqDdilhgPQm5uUWCm6iqfhU0_5JRPsQOOEyc3GBr9F1I2ym0YV3iieS3V6acJRYmU13knFfeGT2heZU9sd5G8LGKk8pmbQ64HvHmP3z6onzfbmqx-drmkPflA/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FASWPO67L7E7MIVCVIMHLJK3U4YXBXANCNFSM5N6IPWJA>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

This message (including any attachments) contains confidential information intended for a specific individual and purpose, and is protected by law. If you are not the intended recipient, you should delete this message and any disclosure, copying, or distribution of this message, or the taking of any action based on it, by you is strictly prohibited.

Deloitte refers to a Deloitte member firm, one of its related entities, or Deloitte Touche Tohmatsu Limited ("DTTL"). Each Deloitte member firm is a separate legal entity and a member of DTTL. DTTL does not provide services to clients. Please see www.deloitte.com/about to learn more.

v.E.1

**Comment by jpassing** [comment] 2022-10-07 01:23
[Release 2.32](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.32.939) includes several fixes related to connection handling. In particular, IAP Desktop can now recover broken/lost connections to IAP in a way that doesn't impact open SSH or RDP sessions. That's a feature gcloud has had for a while, but didn't quite work reliably in previous IAP Desktop versions.

While I'm still unsure what's causing the connectivity issues in your case, I'm optimistic that these changes should improve the situation. I'll therefore close the issue for now, but please reopen it if the connectivity issues still persist with 2.32.

**Closed by jpassing** 2022-10-07 01:23 UTC
Labels: bug
