### ISSUE TITLE
Error code: 2056 - Error in licensing protocol

### ISSUE THREAD

**Issue by shehryarburki** [GoogleCloudPlatform/iap-desktop#571] opened 2021-12-02 00:10 UTC
![image](https://user-images.githubusercontent.com/95257408/144334319-129f7802-93bb-4cc8-96ee-1687b76b1a82.png)

**Comment by jpassing** [comment] 2021-12-02 01:10
This seems to be related to RDS licensing -- is there anything special w.r.t. licensing about the VM you're connecting to? And does this error occur when you run IAP Desktop on a different client machine too?

The issue [might be](https://forum.devolutions.net/topics/24429/the-remote-computer-disconnected-the-session-because-of-an-error-in-th) [caused by](https://kb.parallels.com/en/124829) an inaccessible or corrupted `MSLIcensing` registry key. What you could try is:
1. Delete (or better, temporarily rename) the registry key `HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\MSLicensing`
2. Start IAP Desktop with elevated privileges and try again

**Comment by shehryarburki** [comment] 2021-12-02 08:15
Thanks for your feedback.

Unfortunately I do not have administrator privileges on this machine so I am unable to delete the MSLicensing registry key.

Is there any other way around?

Shehryar

**Comment by shehryarburki** [comment] 2021-12-02 20:16
Hello,

My credentials do work on a different machine when I run IAP desktop.

I did manage to rename the MSLicensing registry key but still getting the same error.

Is there any other way to troubleshoot?

Thanks
Shehryar

**Comment by jpassing** [comment] 2021-12-03 05:48
> My credentials do work on a different machine when I run IAP desktop.

Ok, thanks for verifying. 

> I did manage to rename the MSLicensing registry key but still getting the same error.

Did you launch IAP Desktop with elevated privileges afterwards, and did it recreate the `MSLicensing`key as expected?

Note that because the key is in HKLM, elevated privileges are needed for the RDP control to re-create the key. And as IAP Desktop is a 32-bit app, it should be using the key under `Wow6432Node`.

I haven't seen this particular error before, so it's a bit difficult to give more concrete assistance. But from what I've read elsewhere, it seemed quite likely that the error is related to that key.

Another thing that might be worth trying is to [manually establish a tunnel and use the Microsoft Remote Desktop Client (mstsc)](https://github.com/GoogleCloudPlatform/iap-desktop/wiki/Troubleshooting#other-errors) to see if the same error occurs. It would best to try that with both the 64 bit version  (`c:\Windows\system32\mstsc.exe`) and the 32 bit version (`c:\Windows\SysWOW64\mstsc.exe`).

**Comment by shehryarburki** [comment] 2021-12-03 18:48
Hi Johannes,

I managed to fix the issue. I had to get admin rights from my IT to run the IAP desktop with elevated privileges (after ofcourse renaming the MSLicensing Reg key).

Thanks a lot for your help! Really appreciate.

Shehryar

**Comment by jpassing** [comment] 2021-12-03 20:03
Great, happy to hear that it works now!

Now that you've run the app with elevated privileges once, it should work again without elevated privileges too.

I'll close this issue then.

**Closed by jpassing** 2021-12-03 20:03 UTC
