### ISSUE TITLE
Feature Request: Add equivalent option for "mstsc.exe /admin" switch

### ISSUE THREAD

**Issue by ixniz** [GoogleCloudPlatform/iap-desktop#1326] opened 2024-03-18 13:53 UTC
Add the equivalent option for the "mstsc.exe /admin" switch in the connection settings. 

https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/mstsc

#### Background: 
I have VM instances that are a part of a Remote Desktop deployment with a Connection Broker (CB). 
If you attempt to RDP to any member of the deployment *without* the `/admin` switch the CB will intercept the session and redirect you to a suitable remote desktop server (which may or may not be the one you actually attempted to connect to). 

The `/admin` switch bypasses this and lets you connect to the specified server.

**Comment by jpassing** [comment] 2024-03-18 22:14
Sure, we'll add this.

**Comment by jpassing** [comment] 2024-04-04 03:41
Here's a signed pre-release build that supports a new connection setting, **Session type**:

![image](https://github.com/GoogleCloudPlatform/iap-desktop/assets/5724941/f6d384af-a079-4a0c-aa4a-1193408f2766)

Setting this to **Admin** should have the same effect as using `mstsc /admin`.

- [IapDesktop-2.40.1447-x64-Release.msi](https://issuetracker.google.com/action/issues/332802864/attachments/55232026?download=true)
- [IapDesktop-2.40.1447-x86-Release.msi](https://issuetracker.google.com/action/issues/332802864/attachments/55232027?download=true)

If you have some time, it would be great if you could give it a try.

**Comment by ixniz** [comment] 2024-04-04 12:47
I have installed the pre-release and enabled the Admin session type. Unfortunately it doesn't seem to be working as intended. Connecting to an RDS server that's part of a remote desktop deployment still redirects me to another available member. 

Connecting to the same server using mstsc with /admin logs me in every time.

**Comment by jpassing** [comment] 2024-04-04 20:43
Thanks for the quick feedback, and sorry for wasting your time... I'll look into why this isn't working as intended yet.

**Comment by jpassing** [comment] 2024-04-05 04:27
I missed something in the previous version, here's an updated build:

- [IapDesktop-2.41.1449-x64-Release.msi](https://issuetracker.google.com/action/issues/332802864/attachments/55259770?download=true)
- [IapDesktop-2.41.1449-x86-Release.msi](https://issuetracker.google.com/action/issues/332802864/attachments/55260073?download=true)

Connecting to an RDSH with _Session type_ set to _Admin_ now worked correctly for me.

**Comment by ixniz** [comment] 2024-04-05 08:08
I can confirm that it's now working correctly for me as well. Thanks for doing this update!

**Comment by jpassing** [comment] 2024-04-15 00:38
The feature is now available [in release 2.41](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.41.1463), so I'll close the issue.

Thanks again for suggesting this feature and your feedback!

**Closed by jpassing** 2024-04-15 00:38 UTC
Labels: enhancement, next-release
