### ISSUE TITLE
IAP Desktop - Window Resize issue (Disconnection)

### ISSUE THREAD

**Issue by mvlucilla** [GoogleCloudPlatform/iap-desktop#202] opened 2020-07-14 22:30 UTC
Expected behavior:
On open a virtual machine inside a project using IAP, if i want to resize the window of the VM, i'm facing a disconnection.

Observed behavior:
Every moment when i'm resizing any window.

Installed version: 2.0.86.0
.NET Version: 4.0.30319.42000
OS Version: Microsoft Windows NT 6.2.9200.0

**Comment by jpassing** [comment] 2020-07-17 07:53
Unfortunately, the RDP control does not support resizing [without reconnecting](https://docs.microsoft.com/en-us/windows/win32/termserv/imsrdpclient8-reconnect). Therefore, the expected behavior is:

1. Resize window
1. Reconnect dialog appears for ~2 seconds
1. Session reconnected with new screen size

Is that what you are seeing? Or does the reconnect (2) fail?

**Comment by skad00sh** [comment] 2020-07-23 01:59
The same issue for me as @mvlucilla has said. 
But exactly same like what @jpassing has said.

**Comment by jpassing** [comment] 2020-07-31 06:10
As it turns out, there is a way to do resizing without reconnecting, and this should now be fixed in [2.4.229](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.4.229).

Note that resizing still requires a reconnect if the source or target computer runs an older version of Windows or if the logon has not completed yet -- so depending on circumstances, you still might see the occasional reconnect.

Please re-open the issue if the fix does not work for you.

**Closed by jpassing** 2020-07-31 06:10 UTC
