### ISSUE TITLE
Reduce minimum window size to simplify window snapping on 1080p screens

### ISSUE THREAD

**Issue by chris-tomkins-flexgrid** [GoogleCloudPlatform/iap-desktop#841] opened 2022-11-21 11:18 UTC
OS: Windows 11 22H2 OS Build 22621.819
Environment: 3 monitors, all 1920x1080.
IAP Desktop version: 2.32.939.0
.NET version: 4.8.9105.0

When sizing windows to a small-ish part of the screen (e.g. a quarter-screen, in my most common use-case) IAP Desktop does not properly snap to the area specified - it overlaps the adjacent windows.

All my other apps behave correctly. This is not ideal as it makes it difficult to see the content in other apps' windows seamlessly.

**Comment by jpassing** [comment] 2022-11-27 07:23
Hi Chris,

Sorry for the late response. 

I guess you're seeing something like this?

![image](https://user-images.githubusercontent.com/5724941/204123712-5b0e49ea-53db-4e45-ae93-e3b5a9ff9003.png)

If so, then the issue is that you're trying to resize the window to 960x540 (half of 1920x1080), but IAP Desktop has a minimum window size of 1000x700. I suppose we could change that minimum size to 960x540 (or a bit less, to leave space for the taskbar). Then that quarter-screen layout would work fine for 1920x1080 resolutions. I'd rather not go much below 960x500 though as that'd probably break the layout in some places.

**Comment by chris-tomkins-flexgrid** [comment] 2022-11-28 10:40
Hey, thanks for the reply. Yes, that's exactly what I'm seeing. In my personal case, 960x540 would work perfectly since I don't have a taskbar on that screen, but as you said, a little less would probably be good for other users.

**Comment by jpassing** [comment] 2022-11-28 21:46
Ok, that should be an easy change to make and I'll slot this into the next release (~ January).

**Comment by chris-tomkins-flexgrid** [comment] 2022-11-29 09:11
Thank you!

**Comment by jpassing** [comment] 2023-01-12 23:18
This is now fixed and available in [release 2.34.988](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.34.988). Thanks again for your feedback!

**Closed by jpassing** 2023-01-12 23:18 UTC
Labels: enhancement, scheduled
