### ISSUE TITLE
Shows Restarting all the time.

### ISSUE THREAD

**Issue by Siddhu-Kaulapure** [GoogleCloudPlatform/iap-desktop#511] opened 2021-06-08 09:13 UTC
Expected behavior:
* Step 1
* Step 2
* ...

Observed behavior:
* Step 1
* Step 2
* ...

Installed version: 2.18.631.0
.NET Version: 4.8.4341.0
OS Version: Microsoft Windows NT 10.0.18363.0

**Comment by Siddhu-Kaulapure** [comment] 2021-06-08 09:15
![Screenshot (18)](https://user-images.githubusercontent.com/69795469/121158671-2a7e3400-c868-11eb-8a78-2cade2af18d9.png)

**Comment by jpassing** [comment] 2021-06-09 07:25
Looks like Windows somehow got stuck while trying to restart...  do you see the same issue with multiple VMs? If not, then I don't think it's related to IAP Desktop.

Have you tried if resetting the VM solves the issue? Alternatively, you can use the [interactive serial console](https://cloud.google.com/compute/docs/troubleshooting/troubleshooting-windows#advanced-boot-options) to analyze the state of the VM. If none of that helps, consider filing a GCP support case.

**Comment by jpassing** [comment] 2021-06-24 06:13
I'll close this issue as it seems unrelated to IAP Desktop. Please re-open or file a new issue if you think the issue is indeed specific to IAP Desktop and not related to the VM.

**Closed by jpassing** 2021-06-24 06:13 UTC
