### ISSUE TITLE
IAP Desktop SSH connectivity issue to GCP Ubuntu 22.04 Instances.

### ISSUE THREAD

**Issue by rithac** [GoogleCloudPlatform/iap-desktop#790] opened 2022-09-20 20:14 UTC
I have IAP configured and use it to connect to several instances in GCP. All the pre-requisite permissions  I should need are in place  (IAP-secured Tunnel User, owner, security admin and firewalls allowing  35.235.240.0/20 and it is applied to all instances following the steps at [cloud.google.com/iap/docs/using-tcp-forwarding](https://cloud.google.com/iap/docs/using-tcp-forwarding) and this works flawlessly on all of my other current and new instances created except for anything Ubuntu 22.04 LTS.
I have the relevant firewalls configured to cover all current and any new GCP instances created.  I've created new test instances (Windows, Debian, Citrix, and Ubuntu 20.02 and these continue to allow ssh connectivity as expected, just not when using an instance type of Ubuntu 22.04 and attempting to connect via IAP Desktop.  

I am able to successfully ssh using the GCP Cloud Shell to the Ubuntu 22.04 instance using the command "gcloud computer ssh <googleUsername>@<servername> --tunnel-through-iap"  as well as connecting via the GCP web interface using the ssh button in  Compute Engine by the listed servername, just not via IAP Desktop.

When attempting with IAP Desktop the connection attempt simply shows "connection terminated you do not have sufficient permissions to access this VM instance.  To perform this action, you need the following roles (or an equivalent custom role): 1. 'Computer OS Login' or 'Compute OS Admin Login' 2. 'Service Account User' (if the VM uses a service account) 3. 'Compute OS Login External User' (if the VM belongs to a different GCP organization)

Under 'See details' is the message  SshNativeException:  Username/PublicKey combination invalid
![IAP Desktop Error message](https://user-images.githubusercontent.com/114024725/191354312-cc68e8ed-9195-4219-9e65-99216786453c.JPG)

**Comment by jpassing** [comment] 2022-09-20 22:48
By default, Ubuntu 22.04 doesn't allow RSA for SSH public key authentication anymore, and I suspect that's what's causing the issue.

Could you go to **Tools > Options > SSH** and switch to ECDSA, and try again?

![image](https://user-images.githubusercontent.com/5724941/191377873-74b9d4a4-a8f0-4ab9-aac1-370cd6d9916b.png)


RSA used to be the default setting for IAP Desktop. That changed a few releases ago, but that change didn't apply to existing installations.

**Comment by jpassing** [comment] 2022-09-21 21:36
Glad to hear that it works now!

Let me see if I can improve the error message, it's really not very obvious currently that such errors can be caused by using the wrong type of key. I've created a follow-up issue for that and will close this one.

Johannes

**Closed by jpassing** 2022-09-21 21:36 UTC
