### ISSUE TITLE
IAP issue

### ISSUE THREAD

**Issue by sd250225** [GoogleCloudPlatform/iap-desktop#645] opened 2022-04-05 17:11 UTC
Steps:
* Step 1
* Step 2
* ...

Expected behavior:
Observed behavior:

```System.UnauthorizedAccessException: Access to the path 'Local\IapDesktop_sd250225' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Threading.Mutex.MutexTryCodeHelper.MutexTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.Mutex.CreateMutexWithGuaranteedCleanup(Boolean initiallyOwned, String name, Boolean& createdNew, SECURITY_ATTRIBUTES secAttrs)
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name, Boolean& createdNew, MutexSecurity mutexSecurity)
   at Google.Solutions.IapDesktop.Application.Util.SingletonApplicationBase.Run(String[] args)
   at Google.Solutions.IapDesktop.Program.Main(String[] args)

Installed version: 2.25.755.0
.NET Version: 4.8.4420.0
OS Version: Microsoft Windows NT 10.0.18363.0
```

**Comment by jpassing** [comment] 2022-04-06 06:15
Does this error happen every time you open IAP Desktop, or only occasionally?

If it's reproducible, could you share the entire error message? The error above is missing the first line, which makes it very difficult to guess what the actual error was.

**Comment by jpassing** [comment] 2022-04-12 11:14
I'm able to reproduce this error if I:

1. Launch an **elevated** instance of IAP Desktop.
1. Launch a second instance of IAP Desktop, but without elevation.

   This process crashes immediately (because it can't access the mutex because it's running at a lower IL)


Is this what you did too?

I'll fix this for the next version. Note that IAP Desktop doesn't require elevation - so the easiest way to avoid this issue in the meantime might be to just run the app with normal user privileges.

**Comment by jpassing** [comment] 2022-04-27 11:32
[Version 2.27](https://github.com/GoogleCloudPlatform/iap-desktop/releases/tag/2.27.810) is now available and includes a fix for this issue.

**Closed by jpassing** 2022-04-27 11:32 UTC
